/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.hotelAlura.views;

import com.hotelAlura.Util.InterfaceUtil;
import com.hotelAlura.controllers.UserController;
import javax.swing.JPanel;

/**
 *
 * @author jaime
 */
public class LoginPanel extends javax.swing.JPanel {
    
    private InterfaceUtil interfaceUtil;
    /**
     * Creates new form LoginPanel
     * @param interfaceUtil
     */
    public LoginPanel(InterfaceUtil interfaceUtil) {
        this.interfaceUtil = interfaceUtil;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        aluraLogo = new javax.swing.JLabel();
        labelLogin = new javax.swing.JLabel();
        labelUserName = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        labelUserPassword = new javax.swing.JLabel();
        fieldUserPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        errorLabel = new javax.swing.JLabel();
        labelBackground = new javax.swing.JLabel();

        setBackground(new java.awt.Color(250, 250, 250));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoginPanel.setBackground(new java.awt.Color(250, 250, 250));
        LoginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aluraLogo.setIcon(new javax.swing.ImageIcon("D:\\jaime\\Desktop\\Challengue-Hotel-Alura\\HotelAlura\\src\\main\\java\\com\\hotelAlura\\images\\aH-150px.png")); // NOI18N
        LoginPanel.add(aluraLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 10, -1, -1));

        labelLogin.setBackground(new java.awt.Color(250, 250, 250));
        labelLogin.setFont(new java.awt.Font("Roboto Medium", 1, 48)); // NOI18N
        labelLogin.setForeground(new java.awt.Color(51, 51, 51));
        labelLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogin.setText("Login");
        labelLogin.setPreferredSize(new java.awt.Dimension(127, 60));
        LoginPanel.add(labelLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 400, 60));

        labelUserName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(51, 51, 51));
        labelUserName.setText("Username");
        LoginPanel.add(labelUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 300, 20));

        fieldUserName.setBackground(new java.awt.Color(250, 250, 250));
        fieldUserName.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        fieldUserName.setText("root");
        fieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserNameActionPerformed(evt);
            }
        });
        LoginPanel.add(fieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 300, 30));

        labelUserPassword.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        labelUserPassword.setForeground(new java.awt.Color(51, 51, 51));
        labelUserPassword.setText("Password");
        LoginPanel.add(labelUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 300, 20));

        fieldUserPassword.setBackground(new java.awt.Color(250, 250, 250));
        fieldUserPassword.setText("12345");
        LoginPanel.add(fieldUserPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 300, 30));

        buttonLogin.setBackground(new java.awt.Color(0, 102, 153));
        buttonLogin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        buttonLogin.setForeground(new java.awt.Color(255, 255, 255));
        buttonLogin.setText("Login");
        buttonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        LoginPanel.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 300, 30));

        errorLabel.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        errorLabel.setForeground(new java.awt.Color(255, 0, 51));
        errorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LoginPanel.add(errorLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 300, 30));

        MainPanel.add(LoginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 400, 500));

        labelBackground.setIcon(new javax.swing.ImageIcon("D:\\jaime\\Desktop\\Challengue-Hotel-Alura\\HotelAlura\\src\\main\\java\\com\\hotelAlura\\images\\mainbg.jpg")); // NOI18N
        MainPanel.add(labelBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 720));
    }// </editor-fold>//GEN-END:initComponents

    private void fieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserNameActionPerformed

    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed
        login(fieldUserName.getText(), fieldUserPassword.getText());

    }//GEN-LAST:event_buttonLoginActionPerformed

    public void login (String user, String password){
 
        boolean authenticated = UserController.authenticate(user,password);
        String errorMessage = "Wrong user or password";
        if(authenticated){
            interfaceUtil.showMenuPanel();
        }else{
            errorLabel.setText(errorMessage);
        }   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel aluraLogo;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JPasswordField fieldUserPassword;
    private javax.swing.JLabel labelBackground;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JLabel labelUserPassword;
    // End of variables declaration//GEN-END:variables
}
